Use Status.skipped instead of 'skipped'
to prevent `AttributeError`:

```
Exception AttributeError: 'str' object has no attribute 'name'
Traceback (most recent call last):
  File "/Users/abramowi/python/virtualenvs/behave-py3/bin/behave", line 11, in <module>
    load_entry_point('behave', 'console_scripts', 'behave')()
  File "/Users/abramowi/dev/git-repos/behave/build/lib/behave/__main__.py", line 183, in main
    return run_behave(config)
  File "/Users/abramowi/dev/git-repos/behave/build/lib/behave/__main__.py", line 127, in run_behave
    failed = runner.run()
  File "/Users/abramowi/dev/git-repos/behave/build/lib/behave/runner.py", line 733, in run
    return self.run_with_paths()
  File "/Users/abramowi/dev/git-repos/behave/build/lib/behave/runner.py", line 753, in run_with_paths
    return self.run_model()
  File "/Users/abramowi/dev/git-repos/behave/build/lib/behave/runner.py", line 541, in run_model
    failed = feature.run(self)
  File "/Users/abramowi/dev/git-repos/behave/build/lib/behave/model.py", line 345, in run
    formatter.eof()
  File "/Users/abramowi/dev/git-repos/behave/build/lib/behave/formatter/plain_color.py", line 53, in eof
    self.print_not_executed_steps()
  File "/Users/abramowi/dev/git-repos/behave/build/lib/behave/formatter/plain_color.py", line 99, in print_not_executed_steps
    self.print_step(step, executed=False)
  File "/Users/abramowi/dev/git-repos/behave/build/lib/behave/formatter/plain_color.py", line 64, in print_step
    escapes[status.name] + plain_text + escapes['reset']
AttributeError: 'str' object has no attribute 'name'
```